
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'snowflake_fivetran_vhol'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
# models:
#   my_new_project:
#       # Applies to all files under models/example/
#       example:
#           materialized: view

vars:
    google_ads_schema: 'GOOGLE_ADS_DEMO'

models:
  google_ads_source:
    stg_google_ads__account_history_tmp:
      +enabled: false
    stg_google_ads__account_stats_tmp:
      +enabled: false
    stg_google_ads__ad_group_criterion_history_tmp:
      +enabled: false
    stg_google_ads__ad_group_history_tmp:
      +enabled: false
    stg_google_ads__ad_group_stats_tmp:
      +enabled: false
    stg_google_ads__ad_history_tmp:
      +enabled: false
    stg_google_ads__ad_stats_tmp:
      +enabled: false
    stg_google_ads__campaign_history_tmp:
      +enabled: false
    stg_google_ads__campaign_stats_tmp:
      +enabled: false
    stg_google_ads__keyword_stats_tmp:
      +enabled: false
