version: 2

sources:
  - name: google_ads
    database: PC_FIVETRAN_DB
    schema: GOOGLE_ADS_DEMO
    tables:
      - name: account_history
      - name: account_stats
      - name: ad_history
      - name: ad_stats
      - name: campaign_history
      - name: campaign_stats
      - name: keyword_stats
